behaviors:
  Agent1 Controller:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: C:\Users\lore1\OneDrive - uniroma1.it\Thesis\GameDev - Thesis\ImitationLearning\ImitationPlayerd_6.demo
    behavioral_cloning:
      strength: 0.8
      demo_path: C:\Users\lore1\OneDrive - uniroma1.it\Thesis\GameDev - Thesis\ImitationLearning\ImitationPlayerd_6.demo
      steps: 50000
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
  
  Agent2 Controller:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
